### ISSUE TITLE
Icon in the add-ons manager list is very small

### ISSUE THREAD

**Issue by MikkCZ** [stasm/detach-tabs#1]
The icon in the add-ons manager list is quite small. It's OK in when you open the add-on details. Maybe it is bug in Firefox, I am not sure.
![snimek z 2017-12-04 16-18-59](https://user-images.githubusercontent.com/3941344/33560017-df9b9d66-d90e-11e7-85fb-808b1ddf2415.png)

**Comment by stasm** [comment]
Thanks for reporting this, @MikkCZ! I never got the notification about this issue... I think my Github settings might need some tweaking. Sorry about that.

I noticed this issue as well. I'll investigate. It does look like a Firefox bug.

**Comment by MikkCZ** [comment]
Sorry, clicked wrong button... Thank you for having a look at it.

**Comment by stasm** [comment]
It was my fault after all :) I had accidentally specified the SVG's size as 8x8. Firefox did exactly what it should have.

I fixed the icon in https://github.com/stasm/detach-tabs/commit/9f2d032cdd6ef3566704d1316259dc1ae0976943. I'll publish a new version later today.

**Comment by stasm** [comment]
I published 0.0.3 to AMO yesterday. It fixes the icon sizing in the Add-ons Manager. Thanks again for the report, @MikkCZ!
